---
- name: Cập nhật danh sách các gói
  apt:
    update_cache: yes

- name: Cài đặt Apache và PHP
  apt:
    name:
      - apache2
      - php
      - libapache2-mod-php
      - php-mysql
    state: present

- name: Tạo thư mục cho ứng dụng web
  file:
    path: /var/www/html/pathTraversal
    state: directory
    mode: '0755'

- name: Clone mã nguồn từ GitHub
  git:
    repo: 'https://github.com/hinhlx/pathTraversal.git'
    dest: /var/www/html/pathTraversal
    version: main
    update: yes

- name: Thiết lập quyền truy cập
  file:
    path: /var/www/html/pathTraversal/
    state: directory
    owner: www-data
    group: www-data
    mode: '0755'

- name: Cấu hình Apache để phục vụ ứng dụng
  copy:
    dest: /etc/apache2/sites-available/pathTraversal.conf
    content: |
      <VirtualHost *:8080>
          DocumentRoot /var/www/html/pathTraversal
          <Directory /var/www/html/pathTraversal>
              AllowOverride All
              Require all granted
          </Directory>
      </VirtualHost>

- name: Kích hoạt cấu hình trang web
  shell: |
    a2ensite pathTraversal.conf
    a2dissite 000-default.conf
    systemctl reload apache2

- name: Đảm bảo dịch vụ Apache đang chạy
  service:
    name: apache2
    state: started
    enabled: yes
...