---
# This is a role for setting up the server.

- name: Add user and set password
  user:
    name: '{{ username }}'
    password: '{{ password | password_hash(''sha512'') }}'
    shell: '/bin/bash'

- name: Install packages
  apt:
    pkg:
     - telnetd
    update_cache: yes

- name: Change Telnet port
  replace:
    path: /etc/services
    regexp: '23/tcp'
    replace: '{{ telnet_port }}/tcp'

# xinetd must be installed after changing the Telnet port
- name: Install xinetd package
  apt:
    name: xinetd
- name: Create alias for client
  lineinfile:
    path: '/etc/hosts'
    line: '192.168.30.5 client'

# #setup web_vul:
# - name: Install required packages
#   apt:
#     name:
#       - apt-transport-https
#       - ca-certificates
#       - curl
#       - software-properties-common
#       - git
#     state: present
#     update_cache: yes

# - name: Add Docker’s official GPG key
#   apt_key:
#     url: https://download.docker.com/linux/ubuntu/gpg
#     state: present

# - name: Add Docker repository
#   apt_repository:
#     repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
#     state: present

# - name: Install Docker
#   apt:
#     name: docker-ce
#     state: present
#     update_cache: yes

# - name: Ensure Docker service is started and enabled
#   service:
#     name: docker
#     state: started
#     enabled: yes

# - name: Clone the Git repository containing the Dockerfile
#   git:
#     repo: https://github.com/RewK-Dark/VCW-demo
#     dest: /opt/vcw-demo
#     version: master

# - name: Build Docker image from Dockerfile
#   command: docker build -t cmdi-level01-image .
#   args:
#     chdir: /opt/vcw-demo/cmdi_level1

# - name: Run Docker container from image on port 3001
#   command: docker run -d -p 3001:80 --name cmdi-level01-container cmdi-level01-image

# - name: Open port 3001 for external access
#   ufw:
#     rule: allow
#     port: '3001'
#     proto: tcp
...
